#!/usr/bin/env python3
# Fern-FT8, an FT8 decoder module for FernSDR.
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate src/protocol_tables.cpp from the public-domain protocol files.

The files in protocol/ are the authors' public-domain definitions of FT8
(QEX July/August 2020, reference [14], ft4_ft8_protocols.tgz). This script
reads them and writes the C++ tables, so the tables in the program can be
checked against the files at any time: `python3 tools/gen_tables.py --check`
exits non-zero when src/protocol_tables.cpp differs from what the files give.

Two lookup tables have grown since 2020. The added entries are listed below
with how each was established; see docs/PROTOCOL-SOURCES.md.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROTO = os.path.join(ROOT, "protocol")
OUT = os.path.join(ROOT, "src", "protocol_tables.cpp")

# ARRL/RAC sections renamed or added after 2020 (RAC's 2023 section changes).
# Index is 1-based as in field S7. Each was confirmed by packing
# "K1ABC W9XYZ 6A <section>" with WSJT-X 2.7.0's ft8code and reading S7.
SECTION_CHANGES = {16: "GH", 25: "NS", 44: "TER"}
SECTION_ADDED = ["PE", "NB"]  # 85, 86
# States, provinces and other exchange words after the 2020 table, s13 values
# 8066 to 8171, confirmed the same way with "K1ABC W9XYZ 579 <word>".
STATES_ADDED = ["DR", "FR", "GD", "GR", "OV", "ZH", "ZL"] + ["X%02d" % i for i in range(1, 100)]


def read(name):
    with open(os.path.join(PROTO, name), "r", newline="") as f:
        return f.read().replace("\r\n", "\n")


def generator_rows():
    rows = [ln.strip() for ln in read("generator.dat").split("\n") if re.fullmatch(r"[01]{91}", ln.strip())]
    assert len(rows) == 83, len(rows)
    return rows


def parity_columns():
    cols = []
    for ln in read("parity.dat").split("\n"):
        parts = ln.split()
        if len(parts) == 3 and all(p.isdigit() for p in parts):
            cols.append([int(p) - 1 for p in parts])
    assert len(cols) == 174, len(cols)
    return cols


def quoted_words(name):
    return [w.strip() for w in re.findall(r'"([^"]*)"', read(name))]


def emit():
    out = []
    w = out.append
    w("// Fern-FT8, an FT8 decoder module for FernSDR.")
    w("// SPDX-License-Identifier: GPL-2.0-or-later")
    w("//")
    w("// Generated by tools/gen_tables.py from the public-domain files in protocol/")
    w("// (QEX July/August 2020, reference [14]). Do not edit; run the script.")
    w('#include "protocol.h"')
    w("")
    w("namespace fern::ft8 {")
    w("")
    w("// protocol/generator.dat: row i gives the message-plus-CRC bits summed into")
    w("// parity bit i, 91 bits packed most significant first into 12 bytes.")
    w("const uint8_t kLdpcGenerator[kLdpcM][12] = {")
    for row in generator_rows():
        bits = row + "0" * 5
        by = [int(bits[i:i + 8], 2) for i in range(0, 96, 8)]
        w("    {" + ", ".join("0x%02x" % b for b in by) + "},")
    w("};")
    w("")
    w("// protocol/parity.dat: for codeword bit j, the three parity checks (0-based)")
    w("// that include it.")
    w("const uint8_t kLdpcColumnChecks[kLdpcN][3] = {")
    cols = parity_columns()
    for i in range(0, 174, 6):
        w("    " + " ".join("{%d, %d, %d}," % tuple(c) for c in cols[i:i + 6]))
    w("};")
    w("")
    secs = quoted_words("arrl_rac_sections.txt")
    assert len(secs) == 84, len(secs)
    for idx, name in SECTION_CHANGES.items():
        secs[idx - 1] = name
    secs += SECTION_ADDED
    w("// protocol/arrl_rac_sections.txt, S7 values 1 to 84, with RAC's 2023 changes")
    w("// (16 GH, 25 NS, 44 TER, new 85 PE and 86 NB); see tools/gen_tables.py.")
    w("const char* const kArrlSections[kArrlSectionCount] = {")
    for i in range(0, len(secs), 10):
        w("    " + " ".join('"%s",' % s for s in secs[i:i + 10]))
    w("};")
    w("")
    states = quoted_words("states_provinces.txt")
    assert len(states) == 65, len(states)
    states += STATES_ADDED
    w("// protocol/states_provinces.txt, s13 values 8001 to 8065, then the words")
    w("// added later for 8066 to 8171; see tools/gen_tables.py.")
    w("const char* const kStatesProvinces[kStateCount] = {")
    for i in range(0, len(states), 10):
        w("    " + " ".join('"%s",' % s for s in states[i:i + 10]))
    w("};")
    w("")
    w("}  // namespace fern::ft8")
    return "\n".join(out) + "\n", len(secs), len(states)


def main():
    text, nsec, nstate = emit()
    assert nsec == 86 and nstate == 171, (nsec, nstate)
    if "--check" in sys.argv:
        with open(OUT) as f:
            if f.read() != text:
                print("src/protocol_tables.cpp differs from the protocol files", file=sys.stderr)
                return 1
        return 0
    with open(OUT, "w") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
